apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsphere-capacity-manager-console-plugin
  namespace: vsphere-infra-helpers
  labels:
    app: vsphere-capacity-manager-console-plugin
    app.kubernetes.io/name: vsphere-capacity-manager-console-plugin
    app.kubernetes.io/component: console-plugin
    app.kubernetes.io/part-of: vsphere-capacity-manager
