apiVersion: v1
kind: Service
metadata:
  name: vsphere-capacity-manager-console-plugin
  namespace: vsphere-infra-helpers
  labels:
    app: vsphere-capacity-manager-console-plugin
    app.kubernetes.io/name: vsphere-capacity-manager-console-plugin
    app.kubernetes.io/component: console-plugin
    app.kubernetes.io/part-of: vsphere-capacity-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: vsphere-capacity-manager-console-plugin-cert
spec:
  type: ClusterIP
  selector:
    app: vsphere-capacity-manager-console-plugin
  ports:
  - name: https
    protocol: TCP
    port: 9443
    targetPort: 9443
  sessionAffinity: None
